In [ ]:
import numpy as np

In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
print(B.ravel())
print(B.flatten())
print(B.transpose())


# B.dtype

# mx_once=np.ones((2,3))

# mx_list = mx_once.tolist()

# dtypess = mx_once.dtype

# print(mx_list)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [ ]:
mx_list = mx_once.tolist()
print(mx_list)

[[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]


In [ ]:
np.arange(1,11,1).reshape(2, 5)
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:


A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

result = np.vstack((A, B))
print(np.hstack((A, B)))

print(result)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
A = np.array([10, 20, 30])
B = np.array([1, 2, 3])
print(A+B)
print(A-B)
print(A*B)
print(A//B)

[11 22 33]
[ 9 18 27]
[10 40 90]
[10 10 10]
